import assert from 'node:assert/strict';
import {load} from './load-ts.mjs';
const roster=load('lib/roster.ts'),engine=load('lib/action-engine.ts');
const batter={id:'2026:54400',playerId:'54400',name:'DB 타자',team:'HH',pa:100,ab:90,h:30,hr:4,so:10,avg:.333,slg:.533,ops:.9,profile:{batsThrows:'좌투좌타',bats:'L',throws:'L',heightCm:180},discipline:{zoneSwingRate:.7,chaseRate:.2,zoneContactRate:.9,outZoneContactRate:.6}};
const pitcher={id:'2026:55730',playerId:'55730',name:'DB 투수',team:'SK',tbf:100,bb:20,so:30,outs:90,er:10,era:3,whip:1.2,profile:{batsThrows:'좌투좌타',bats:'L',throws:'L',heightCm:190},discipline:{zonePitchRate:.5},arsenal:[{type:'sinker',velocity:139.2,usage:100}],arsenalSource:'observed'};
const data={season:2026,seasons:[2026,2025],asOf:'2026-09-11',revision:'one',teams:[{code:'HH',name:'한화'},{code:'SK',name:'SSG'}],batters:[batter],pitchers:[pitcher]};
roster.registerRoster(roster.parseRoster(data));
assert.equal(engine.batterStats(batter.id).name,'DB 타자');assert.equal(engine.pitcherStats(pitcher.id).TBF,100);
assert.deepEqual(engine.attributes(batter.id,pitcher.id),{contact:83,power:68,control:30,strikeout:72});
assert.deepEqual(engine.arsenal(pitcher.id),pitcher.arsenal);assert(engine.throwsLeft(pitcher.id));assert(engine.batsLeft(batter.id,pitcher.id));
assert.throws(()=>engine.batterStats('2027:54400'));assert.throws(()=>engine.pitcherStats('2027:55730'));assert.throws(()=>engine.arsenal('2027:55730'));
const snapshot={season:2026,asOf:data.asOf,revision:data.revision,batter:structuredClone(batter),pitcher:structuredClone(pitcher)};
roster.pinMatchRoster(snapshot);
const refreshed=structuredClone(data);refreshed.revision='two';refreshed.batters[0].so=80;refreshed.pitchers[0].bb=0;refreshed.pitchers[0].profile.throws='R';refreshed.pitchers[0].arsenal[0].velocity=151;
roster.registerRoster(roster.parseRoster(refreshed));
assert.deepEqual(engine.attributes(batter.id,pitcher.id),{contact:83,power:68,control:30,strikeout:72});
assert.equal(engine.arsenal(pitcher.id)[0].velocity,139.2);assert(engine.throwsLeft(pitcher.id));
roster.pinMatchRoster(null);assert.equal(engine.attributes(batter.id,pitcher.id).contact,25);assert.equal(engine.attributes(batter.id,pitcher.id).control,95);assert(!engine.throwsLeft(pitcher.id));
roster.registerRoster(roster.parseRoster({...data,batters:[],pitchers:[]}));
assert.throws(()=>engine.batterStats(batter.id));
roster.pinMatchRoster(snapshot);assert.equal(engine.batterStats(batter.id).PA,100);assert.equal(engine.arsenal(pitcher.id)[0].velocity,139.2);
const pitch={id:1,type:'sinker',velocity:139.2,releaseAt:1000,flightMs:400,target:{x:0,y:0},breakX:0,breakY:0,quality:1,resolved:false,bodyHit:null};
const view={batter:batter.id,pitcher:pitcher.id,pace:'practice',pitch};
assert.equal(engine.evaluatePitch(view,null,1400).outcome,'STRIKE','Restored match predicts using its snapshot without loading a roster');
roster.pinMatchRoster(null);assert.equal(engine.batterStats('54400').id,'54400','Legacy games retain their own existing snapshot dataset');
const duplicate={...batter,id:'2026:99999',playerId:'99999',team:'SK'};
assert.deepEqual(roster.filterPlayers([batter,duplicate],'SK',' DB ').map(x=>x.id),[duplicate.id]);
assert.deepEqual(roster.filterPlayers([batter,duplicate],'','없는 선수'),[]);
assert.equal(roster.preserveSelection([batter,duplicate],duplicate.id),duplicate.id);
assert.equal(roster.preserveSelection([batter],'2025:54400'),batter.id);assert.equal(roster.preserveSelection([],batter.id),'');
assert.equal(roster.teamName('SK',data.teams),'SSG');assert.equal(roster.teamName('WO'),'키움');assert.equal(roster.numberLabel(null,2),'—');
const namesake={...batter,id:'2026:99999',playerId:'99999',profile:{batsThrows:'우투우타'}};
const twins=[batter,namesake],labels=twins.map(player=>roster.playerOptionLabel(player,twins,data.teams));
assert.notEqual(labels[0],labels[1]);assert(labels[0].includes('54400')&&labels[1].includes('99999'));
assert(labels[0].includes('좌투좌타')&&labels[1].includes('우투우타'));
assert.equal(roster.playerOptionLabel(batter,[batter],data.teams),'DB 타자 · 한화');
const unknownNamesake={...namesake,profile:{batsThrows:'미상'}},sameHands={...namesake,profile:batter.profile};
assert(roster.playerOptionLabel(unknownNamesake,[batter,unknownNamesake],data.teams).includes('99999'));
assert.notEqual(roster.playerOptionLabel(batter,[batter,sameHands],data.teams),roster.playerOptionLabel(sameHands,[batter,sameHands],data.teams));
assert.throws(()=>roster.parseRoster({...data,batters:[{...batter,pa:0}]}));assert.throws(()=>roster.parseRoster({...data,pitchers:[{...pitcher,arsenal:[]}]}));
assert.throws(()=>roster.parseRoster({...data,batters:[{...batter,id:'54400'}]}));assert.throws(()=>roster.parseRoster({...data,batters:[batter,batter]}));
const missing={...data,batters:[{...batter,profile:{batsThrows:''}}],pitchers:[{...pitcher,profile:{batsThrows:''},era:null,whip:null,arsenalSource:'default'}]};
roster.registerRoster(roster.parseRoster(missing));assert.equal(engine.batterHandLabel(batter.id,pitcher.id),'타석 정보 없음');assert.equal(engine.pitcherHandLabel(pitcher.id),'투구손 정보 없음');
for(const description of ['정보 없음','미상','우투']){
 missing.batters[0].profile={batsThrows:description};missing.pitchers[0].profile={batsThrows:description==='우투'?'미상':description};roster.registerRoster(roster.parseRoster(missing));
 assert.equal(engine.batterHandLabel(batter.id,pitcher.id),'타석 정보 없음');assert.equal(engine.pitcherHandLabel(pitcher.id),'투구손 정보 없음');
}
console.log('PASS DB season identities, dynamic stats/arsenal/handedness, frozen match snapshot across DB refresh and unavailable roster, legacy-only fallback, filters/selection, empty/null/malformed records');
