import { build } from "esbuild";
import { copyFile, mkdir, readFile, readdir, stat, unlink, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const project = path.dirname(fileURLToPath(import.meta.url));
const output = path.resolve(project, "../frontend/diamond");
const require = createRequire(import.meta.url);
const loaders = { ".tsx": "tsx", ".ts": "ts", ".js": "jsx", ".mjs": "js", ".cjs": "js", ".json": "json", ".css": "css" };
function insideProject(file) {
  const relative = path.relative(project, file);
  if (relative.startsWith("..") || path.isAbsolute(relative)) throw new Error(`게임 소스 폴더 외부 참조: ${file}`);
  return file;
}
async function sourceFile(target) {
  for (const candidate of [target, ...Object.keys(loaders).map(ext => target + ext), ...Object.keys(loaders).map(ext => path.join(target, "index" + ext))]) {
    insideProject(candidate);
    try { if ((await stat(candidate)).isFile()) return candidate; } catch (error) { if (error.code !== "ENOENT" && error.code !== "ENOTDIR") throw error; }
  }
  throw new Error(`게임 소스를 찾을 수 없습니다: ${target}`);
}
// Read only this project's sources. This also avoids native directory scans above the workspace on restricted Windows hosts.
const projectSources = {
  name: "diamond-project-sources",
  setup(builder) {
    builder.onResolve({ filter: /.*/ }, async args => {
      if (args.kind === "url-token" && /^(\/|https?:|data:)/.test(args.path)) return { path: args.path, external: true };
      let target;
      if (path.isAbsolute(args.path)) target = args.path;
      else if (args.path.startsWith(".")) target = path.resolve(path.dirname(path.resolve(project, args.importer)), args.path);
      else {
        const parts = args.path.split("/");
        const packageName = parts.slice(0, args.path.startsWith("@") ? 2 : 1).join("/");
        const packageRoot = path.join(project, "node_modules", packageName);
        const metadata = JSON.parse(await readFile(insideProject(path.join(packageRoot, "package.json")), "utf8"));
        target = args.path === packageName && metadata.module ? path.join(packageRoot, metadata.module) : require.resolve(args.path);
      }
      return { path: path.relative(project, await sourceFile(target)).split(path.sep).join("/"), namespace: "diamond-source" };
    });
    builder.onLoad({ filter: /.*/, namespace: "diamond-source" }, async args => {
      const loader = loaders[path.extname(args.path)];
      if (!loader) throw new Error(`지원하지 않는 게임 소스 형식: ${args.path}`);
      return { contents: await readFile(insideProject(path.resolve(project, args.path)), "utf8"), loader };
    });
  }
};
const result = await build({
  absWorkingDir: project,
  entryPoints: [path.join(project, "app/entry.tsx")],
  tsconfigRaw: { compilerOptions: { jsx: "react-jsx", target: "ES2022" } },
  outdir: output,
  entryNames: "assets/game-[hash]",
  assetNames: "assets/[name]-[hash]",
  bundle: true,
  write: false,
  metafile: true,
  minify: true,
  sourcemap: false,
  format: "esm",
  platform: "browser",
  target: ["es2022"],
  jsx: "automatic",
  charset: "utf8",
  legalComments: "external",
  plugins: [projectSources],
  define: { "process.env.NODE_ENV": '"production"' },
  logLevel: "info"
});
const relativeUrl = file => "./" + path.relative(output, file.path).split(path.sep).join("/");
const script = result.outputFiles.find(file => file.path.endsWith(".js"));
const style = result.outputFiles.find(file => file.path.endsWith(".css"));
if (!script || !style) throw new Error("게임 JavaScript/CSS 출력이 없습니다.");

for (const file of result.outputFiles) {
  const relative = path.relative(output, file.path);
  if (relative.startsWith("..") || path.isAbsolute(relative)) throw new Error("게임 출력 폴더 외부에는 쓸 수 없습니다.");
  await mkdir(path.dirname(file.path), { recursive: true });
  await writeFile(file.path, file.contents);
}
async function copyPublic(source, destination) {
  await mkdir(destination, { recursive: true });
  for (const file of await readdir(source, { withFileTypes: true })) {
    if (file.isDirectory()) await copyPublic(path.join(source, file.name), path.join(destination, file.name));
    else if (file.isFile()) await copyFile(path.join(source, file.name), path.join(destination, file.name));
  }
}
await copyPublic(path.join(project, "public"), output);
const template = await readFile(path.join(project, "index.html"), "utf8");
if (!template.includes("<!-- diamond-styles -->") || !template.includes("<!-- diamond-script -->")) throw new Error("게임 HTML의 번들 삽입 위치가 없습니다.");
await writeFile(path.join(output, "index.html"), template
  .replace("<!-- diamond-styles -->", `<link rel="stylesheet" href="${relativeUrl(style)}">`)
  .replace("<!-- diamond-script -->", `<script type="module" src="${relativeUrl(script)}"></script>`));

// Only remove obsolete files generated by this build; public files and other frontend pages are untouched.
const generated = new Set(result.outputFiles.map(file => path.basename(file.path)));
const assets = path.join(output, "assets");
for (const file of await readdir(assets, { withFileTypes: true })) {
  if (file.isFile() && /^game-[A-Z0-9]+\.(?:js|css)(?:\.LEGAL\.txt)?$/.test(file.name) && !generated.has(file.name))
    await unlink(path.join(assets, file.name));
}
const size = result.outputFiles.reduce((sum, file) => sum + file.contents.length, 0);
console.log(`Built /diamond/index.html · ${(size / 1024).toFixed(1)} KiB JS/CSS · ${Object.keys(result.metafile.inputs).length} source modules`);
