<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <AssemblyName>NaverRelay.Application</AssemblyName>
    <RootNamespace>NaverRelay.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NaverRelay.Parser\NaverRelay.Parser.csproj" />
  </ItemGroup>
</Project>
