<Project>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>false</ContinuousIntegrationBuild>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Version>2.6.0-preview</Version>
    <Authors>Naver Sabermetrics Project</Authors>
  </PropertyGroup>
</Project>
