import {useState,useCallback,useEffect} from 'react';
import {Users,Play,Copy,ArrowRight} from 'lucide-react';
import {useMatchClient,rememberedMatch} from '../lib/match-client';
import {useSeasonPresentation,seasonPitchKey} from '../lib/season-presentation';
import {PACE_SETTINGS,type Pace} from '../lib/action-engine';
import {teamName,fullGameTeams,type RosterResponse} from '../lib/roster';
import SeasonMatch from './season-match';
import {TeamManagement} from './team-management';

export default function ExhibitionPage({roster,loadRoster,suspended=false,active=true}:{roster:RosterResponse|null;loadRoster:(season?:number)=>Promise<RosterResponse>;suspended?:boolean;active?:boolean}){
 const {state,busy,error,setError,restoring,command:requestCommand,clock,reset}=useMatchClient(active&&!suspended);
 const [immediatePitch,setImmediatePitch]=useState<string|null>(null);
 const presentation=useSeasonPresentation(state,clock,immediatePitch,active);
 const command=useCallback(async(body:Record<string,unknown>)=>{const result=await requestCommand(body);if(String(body.op).startsWith('sim-'))setImmediatePitch(seasonPitchKey(result));return result;},[requestCommand]);
 const [hostTeam,setHostTeam]=useState('LG'),[guestTeam,setGuestTeam]=useState('OB'),[mode,setMode]=useState<'ai'|'pvp'>('pvp'),[pace,setPace]=useState<Pace>('practice');
 const [code,setCode]=useState(rememberedMatch()),[copied,setCopied]=useState(false),[yearBusy,setYearBusy]=useState(false);
 const teams=fullGameTeams(roster),eligible=teams.some(t=>t.code===hostTeam)&&teams.some(t=>t.code===guestTeam);
 useEffect(()=>{if(state)return;const available=fullGameTeams(roster);const home=available.some(t=>t.code===hostTeam)?hostTeam:available[0]?.code??'';const away=available.some(t=>t.code===guestTeam)&&guestTeam!==home?guestTeam:available.find(t=>t.code!==home)?.code??'';setHostTeam(home);setGuestTeam(away);},[roster,state?.match.code]);
 const send=(op:string,extra:Record<string,unknown>={})=>{if(presentation.pending)return;void command({op,...extra}).catch(()=>{});};
 const share=async()=>{try{await navigator.clipboard.writeText(location.origin+location.pathname+'?room='+state!.match.code);setCopied(true);}catch{setError('경기 코드를 직접 복사해 주세요.');}};
 return <div className="exhibition-page"><div className="season-section-heading"><div><span>EXHIBITION · NINE INNINGS</span><h1>친구와 한 경기.</h1><p>각자 구단을 맡아 타격과 투구를 오가며 9이닝을 겨룹니다.</p></div>{state&&<button disabled={busy||presentation.pending} onClick={reset}>새 경기 설정</button>}</div>
  {error&&<div className="season-error" role="alert"><span>{error}</span><button onClick={()=>setError('')} aria-label="친선 알림 닫기">×</button></div>}
  {!state?<div className="exhibition-setup"><section className="season-panel season-settings"><h2><Users size={20}/>친선 경기 만들기</h2><div className="season-segment"><button className={mode==='pvp'?'selected':''} onClick={()=>setMode('pvp')}>친구와 PvP</button><button className={mode==='ai'?'selected':''} onClick={()=>setMode('ai')}>AI와 한 경기</button></div><div className="season-form-grid"><label>우리 구단<select value={hostTeam} onChange={e=>setHostTeam(e.target.value)}>{teams.map(t=><option key={t.code} value={t.code}>{t.name}</option>)}</select></label><label>상대 구단<select value={guestTeam} onChange={e=>setGuestTeam(e.target.value)}>{teams.map(t=><option key={t.code} value={t.code}>{t.name}</option>)}</select></label></div><label>선수 기록<select value={roster?.season??''} disabled={yearBusy||busy} onChange={e=>{setYearBusy(true);void loadRoster(Number(e.target.value)).catch(e=>setError(e.message)).finally(()=>setYearBusy(false));}}>{roster?.seasons.map(y=><option key={y} value={y}>{y} 정규시즌</option>)}</select></label><label>게임 속도<select value={pace} onChange={e=>setPace(e.target.value as Pace)}>{(Object.keys(PACE_SETTINGS) as Pace[]).map(p=><option key={p} value={p}>{PACE_SETTINGS[p].label}</option>)}</select></label>{roster&&teams.length<2&&<p className="season-note" role="status">친선 경기에는 타자 9명과 투수 1명 이상의 기록을 갖춘 두 구단이 필요합니다.</p>}{hostTeam===guestTeam&&<p className="season-note">서로 다른 구단을 선택해 주세요.</p>}<button className="season-primary" disabled={!roster||busy||restoring||yearBusy||!eligible||hostTeam===guestTeam} onClick={()=>send('create',{season:roster?.season,hostTeam,guestTeam,mode,pace})}>{mode==='pvp'?'대결방 만들기':'AI 경기 시작'} <ArrowRight size={17}/></button></section>
   <section className="season-panel exhibition-join"><span>HAVE AN INVITE?</span><h2>초대받은 경기에 참가</h2><p>친구에게 받은 8자리 코드를 입력하세요.<br/>다른 브라우저나 기기에서 접속하면 상대 구단으로 참가합니다.</p><form onSubmit={e=>{e.preventDefault();send('join',{code:code.trim().toUpperCase()});}}><label>경기 코드<input value={code} maxLength={8} placeholder="FXXXXXXX" autoComplete="off" onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''))}/></label><button className="season-primary" disabled={busy||presentation.pending||restoring||code.length!==8}>경기 참가 <Play size={16}/></button></form><p className="season-note">친선 경기는 리그 순위와 커리어 기록에 반영되지 않습니다. 진행 기록은 하루 동안 유지됩니다.</p></section></div>:<>
   <div className="exhibition-match-bar"><div><span>{state.match.mode==='pvp'?'친구 PvP':'AI 친선'} · {state.save?.season} 기록</span><strong>{teamName(state.match.team)} <small>YOUR TEAM</small></strong></div><div><code>{state.match.code}</code><button onClick={()=>void share()}><Copy size={14}/>{copied?'링크 복사됨':'초대 링크 복사'}</button></div></div>
   {state.match.waiting&&<div className="exhibition-waiting"><Users size={24}/><div><b>{teamName(state.match.guestTeam)}을 맡을 친구를 기다리고 있습니다</b><span>위 코드나 초대 링크를 공유하면 입장 후 경기를 시작할 수 있습니다.</span></div></div>}
   {state.action&&state.save?.game&&<div className="season-game-layout"><SeasonMatch active={active} key={state.match.code} state={state} immediatePitch={immediatePitch} busy={busy} suspended={suspended} clock={clock} command={command} appearances={state.appearances??{}} friendly onNewGame={reset}/><aside>{!state.match.waiting&&!presentation.masked&&presentation.state?.save&&<TeamManagement save={presentation.state.save} busy={busy||presentation.pending} send={send} pitchInFlight={presentation.pending||!!state.action?.pitch&&!state.action.pitch.resolved}/>}<section className="season-panel"><h2>9이닝 친선 경기</h2><p className="season-note">공격할 때는 타격, 수비할 때는 투구를 조작합니다. 3아웃이면 공수가 바뀌며 연장 12회까지 승부를 가릅니다.</p>{state.match.mode==='ai'&&(presentation.pending||!state.save.game.complete)&&<div className="season-auto-actions"><button disabled={busy||presentation.pending} onClick={()=>send('sim-half')}>이번 공수 자동 진행</button><button disabled={busy||presentation.pending} onClick={()=>send('sim-game')}>경기 자동 완료</button></div>}<p className="season-note">연결이 끊겨도 같은 브라우저로 코드에 다시 접속하면 이어서 할 수 있습니다.</p></section></aside></div>}
  </>}
 </div>;
}
