"use client";
import {useState,useRef,useEffect,useCallback,useMemo} from "react";
import {ArrowRight,ArrowUpRight,ChevronDown,Copy,Crosshair,Maximize2,MousePointer2,RotateCcw,Target,Users,Volume2,VolumeX,X,Zap,CircleHelp,Loader2,Trophy} from "lucide-react";
import ActionScene,{LocalSwing} from "./action-scene";
import {RosterResponse,parseRoster,registerRoster,pinMatchRoster,rosterBatter,rosterPitcher,filterPlayers,preserveSelection,teamName,playerOptionLabel,numberLabel} from "../lib/roster";
import {ActionView,Side,Pace,Vec,PitchType,PACE_SETTINGS,PITCH_NAMES,arsenal,attributes,batterStats,pitcherStats,clamp,batterHandLabel,pitcherHandLabel} from "../lib/action-engine";

import {SWING_CONTACT_MS} from "../lib/player-motion";
import {localNow,createClockSync} from "../lib/game-clock";

export default function Home(){
 const [tabActive,setTabActive]=useState(!document.hidden),csrf=useRef<string|null>(null);
 useEffect(()=>{
  const receive=(event:MessageEvent)=>{if(event.origin===location.origin&&event.source===window.parent&&event.data?.type==="saber:visibility")setTabActive(event.data.active===true)};
  const visibility=()=>{if(document.hidden)setTabActive(false);else if(window.parent===window)setTabActive(true)};
  const resize=()=>window.parent.postMessage({type:"diamond:height",height:Math.ceil(document.body.getBoundingClientRect().height)},location.origin);
  window.addEventListener("message",receive);document.addEventListener("visibilitychange",visibility);
  const observer=new ResizeObserver(resize);observer.observe(document.body);resize();
  return()=>{observer.disconnect();window.removeEventListener("message",receive);document.removeEventListener("visibilitychange",visibility)};
 },[]);
 const [side,setSide]=useState<Side>("batter"),[mode,setMode]=useState<"ai"|"pvp">("ai"),[batter,setBatter]=useState(""),[pitcher,setPitcher]=useState(""),[pace,setPace]=useState<Pace>("practice");
 const [game,setGame]=useState<ActionView|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[connected,setConnected]=useState(true),[room,setRoom]=useState(""),[copied,setCopied]=useState(false),[ready3d,setReady3d]=useState<boolean|null>(null);
 const [pitchType,setPitchType]=useState<PitchType>("fastball"),[swingTime,setSwingTime]=useState(-100000),[charging,setCharging]=useState(false),[chargeStarted,setChargeStarted]=useState(0),[now,setNow]=useState(localNow()),[sound,setSound]=useState(true);
 const [localSwing,setLocalSwing]=useState<LocalSwing|null>(null);const playedContacts=useRef(new Set<string>());
 const [roster,setRoster]=useState<RosterResponse|null>(null),[seasonRequest,setSeasonRequest]=useState<number|null>(null),[rosterLoading,setRosterLoading]=useState(true),[rosterError,setRosterError]=useState(""),[rosterRetry,setRosterRetry]=useState(0),[restoring,setRestoring]=useState(()=>!!new URLSearchParams(location.search).get("match"));
 const [batterTeam,setBatterTeam]=useState(""),[pitcherTeam,setPitcherTeam]=useState(""),[batterSearch,setBatterSearch]=useState(""),[pitcherSearch,setPitcherSearch]=useState("");
 const aim=useRef<Vec>({x:0,y:0}),clock=useRef(0),clockSync=useRef(createClockSync()),liveGame=useRef(game),lock=useRef(false),generation=useRef(0),dialog=useRef<HTMLDialogElement>(null),stage=useRef<HTMLDivElement>(null),soundRef=useRef(sound),audio=useRef<AudioContext|null>(null),chargeRef=useRef<number|null>(null);
 liveGame.current=game;soundRef.current=sound;
 useEffect(()=>{
  if(game)return;
  const controller=new AbortController();let active=true;
  setRosterLoading(true);setRosterError("");setRoster(null);setReady3d(null);
  void fetch("/api/diamond/roster"+(seasonRequest?"?season="+seasonRequest:""),{signal:controller.signal,credentials:"same-origin",cache:"no-store"}).then(async response=>{
   const body=await response.json();if(!response.ok)throw new Error(body.error??body.message??"선수 기록을 불러오지 못했습니다.");return parseRoster(body);
  }).then(data=>{if(!active)return;registerRoster(data);setRoster(data);setBatterTeam(team=>data.teams.some(t=>t.code===team)?team:"");setPitcherTeam(team=>data.teams.some(t=>t.code===team)?team:"");}).catch(error=>{if(active&&!controller.signal.aborted)setRosterError(error instanceof Error?error.message:"선수 기록을 불러오지 못했습니다.");}).finally(()=>{if(active)setRosterLoading(false)});
  return()=>{active=false;controller.abort()};
 },[seasonRequest,rosterRetry,!!game]);
 const filteredBatters=useMemo(()=>filterPlayers(roster?.batters??[],batterTeam,batterSearch),[roster,batterTeam,batterSearch]),filteredPitchers=useMemo(()=>filterPlayers(roster?.pitchers??[],pitcherTeam,pitcherSearch),[roster,pitcherTeam,pitcherSearch]);
 useEffect(()=>{if(game||!roster)return;setBatter(current=>preserveSelection(filteredBatters,current))},[filteredBatters,roster,!!game]);
 useEffect(()=>{if(game||!roster)return;setPitcher(current=>preserveSelection(filteredPitchers,current))},[filteredPitchers,roster,!!game]);
 const b=(()=>{if(!batter||(!game&&!roster?.batters.some(player=>player.id===batter)))return null;try{return batterStats(batter)}catch{return null}})(),p=(()=>{if(!pitcher||(!game&&!roster?.pitchers.some(player=>player.id===pitcher)))return null;try{return pitcherStats(pitcher)}catch{return null}})();
 const ratings=b&&p?attributes(batter,pitcher):null,pitches=p?arsenal(pitcher):[],active=game?.pitch,last=active?.reaction;
 const batterSource=b?rosterBatter(batter):undefined,pitcherSource=p?rosterPitcher(pitcher):undefined;
 const selectedSeason=game?(game.roster?.season??null):roster?.season??seasonRequest;
 useEffect(()=>{if(pitches.length&&!pitches.some(item=>item.type===pitchType))setPitchType(pitches[0].type)},[pitcher,roster,game?.code,pitchType]);
 const waiting=!!game?.waiting,done=!!game?.done,isFlying=!!active&&!active.resolved&&now>=active.releaseAt,canPitch=!!game&&!done&&!waiting&&!busy&&(!active||active.resolved&&now>Math.max(active.releaseAt+active.flightMs,last?.at??0)+1000),canSwing=!!game&&side==="batter"&&!done&&!waiting&&!busy&&!!active&&!active.resolved&&now>=active.releaseAt-120;
 const progress=charging?((now-chargeStarted)%1400)/1400:0;
 function tone(kind:"swing"|"hit"|"pitch"){if(!soundRef.current)return;try{const ac=audio.current??new AudioContext();audio.current=ac;if(ac.state==="suspended")void ac.resume();const n=ac.currentTime;
  if(kind==="hit"){const buffer=ac.createBuffer(1,Math.ceil(ac.sampleRate*.045),ac.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.exp(-i/ac.sampleRate*140);const crack=ac.createBufferSource(),filter=ac.createBiquadFilter(),volume=ac.createGain();crack.buffer=buffer;filter.type="bandpass";filter.frequency.value=2300;filter.Q.value=.7;volume.gain.value=.55;crack.connect(filter);filter.connect(volume);volume.connect(ac.destination);crack.start(n);}
  const osc=ac.createOscillator(),gain=ac.createGain();osc.connect(gain);gain.connect(ac.destination);osc.type=kind==="hit"?"triangle":"sine";osc.frequency.setValueAtTime(kind==="hit"?1350:kind==="swing"?240:380,n);osc.frequency.exponentialRampToValueAtTime(kind==="hit"?240:70,n+(kind==="hit"?.045:.13));gain.gain.setValueAtTime(kind==="hit"?.22:.055,n);gain.gain.exponentialRampToValueAtTime(.001,n+(kind==="hit"?.055:.16));osc.start(n);osc.stop(n+(kind==="hit"?.07:.18));}catch{}}
 const contactSound=useCallback((key:string)=>{if(playedContacts.current.has(key))return;playedContacts.current.add(key);tone("hit")},[]);
 const apply=useCallback((v:ActionView,gen:number)=>{if(gen!==generation.current)return;if((v.batter.includes(":")||v.pitcher.includes(":"))&&(!v.roster||v.roster.batter.id!==v.batter||v.roster.pitcher.id!==v.pitcher))throw new Error("대결의 선수 기록을 복구하지 못했습니다.");pinMatchRoster(v.roster??null);batterStats(v.batter);pitcherStats(v.pitcher);if(v.roster)setSeasonRequest(v.roster.season);setGame(old=>{if(old?.code===v.code&&(v.pitchCount<old.pitchCount||v.pitchCount===old.pitchCount&&v.history.length<old.history.length))return old;return v});setBatter(v.batter);setPitcher(v.pitcher);setSide(v.role);setMode(v.mode);setPace(v.pace);history.replaceState(null,"","?match="+v.code)},[]);
 async function request(body?:unknown,code?:string){
  if(body&&!csrf.current){const session=await fetch("/api/session",{credentials:"same-origin",cache:"no-store"});if(!session.ok)throw new Error("게임 연결을 준비하지 못했습니다. 다시 시도해 주세요.");csrf.current=(await session.json()).csrfToken}
  const start=localNow(),gen=generation.current,response=await fetch(code?"/api/diamond/action?code="+encodeURIComponent(code):"/api/diamond/action",{method:body?"POST":"GET",credentials:"same-origin",headers:body?{"Content-Type":"application/json","X-CSRF-TOKEN":csrf.current??""}:undefined,body:body?JSON.stringify(body):undefined,cache:"no-store"});
  const v=await response.json() as ActionView&{error?:string;message?:string;code?:string};if(!response.ok){if(v.code==="CSRF")csrf.current=null;throw new Error(v.error??v.message??"연결을 확인해 주세요.")}
  const end=localNow();if(gen===generation.current&&v.serverReceivedAt!==undefined&&v.serverSentAt!==undefined){const offset=clockSync.current.sample({clientStart:start,clientEnd:end,serverReceived:v.serverReceivedAt,serverSent:v.serverSentAt});if(offset!==null&&(!liveGame.current?.pitch||liveGame.current.pitch.resolved)){clock.current=offset;setNow(localNow()+offset)}}return v
 }
 async function run(body:unknown){if(lock.current)throw new Error("처리 중입니다.");lock.current=true;setBusy(true);setError("");const gen=generation.current;try{const v=await request(body);apply(v,gen);setConnected(true);return v}catch(e){if(gen===generation.current)setError(e instanceof Error?e.message:"다시 시도해 주세요.");throw e}finally{lock.current=false;setBusy(false)}}
 async function start(){if(!ready3d||!roster||!b||!p||rosterLoading||restoring)return;try{const v=await run({op:"create",mode,role:side,batter,pitcher,pace,season:roster.season});setPitchType(arsenal(v.pitcher)[0].type);aim.current={x:0,y:0};return v}catch{return null}}
 async function join(){try{const v=await run({op:"join",code:room.trim().toUpperCase()});setPitchType(arsenal(v.pitcher)[0].type)}catch{}}
 function reset(){if(lock.current)return;generation.current++;pinMatchRoster(null);setGame(null);setError("");setCharging(false);chargeRef.current=null;setSwingTime(-100000);setLocalSwing(null);playedContacts.current.clear();history.replaceState(null,"",location.pathname)}
 async function askPitch(){const g=liveGame.current;if(!g)return;try{await run({op:"ready",code:g.code,previousPitch:g.pitchCount})}catch{}}
 const current=useRef({canSwing,canPitch,pitchType,side,run});current.current={canSwing,canPitch,pitchType,side,run};
 const swing=useCallback(()=>{const g=liveGame.current;if(!g?.pitch||!current.current.canSwing)return;const started=localNow()+clock.current,at=started+SWING_CONTACT_MS,frozenAim={...aim.current};setLocalSwing({code:g.code,pitchId:g.pitch.id,at,aim:frozenAim});setSwingTime(started);tone("swing");void current.current.run({op:"swing",code:g.code,pitchId:g.pitch.id,inputAt:started,at,aim:frozenAim}).catch(()=>{setLocalSwing(old=>old?.at===at?null:old)})},[]);
 const beginCharge=useCallback(()=>{if(current.current.side!=="pitcher"||!current.current.canPitch||chargeRef.current!==null)return;const time=localNow()+clock.current;chargeRef.current=time;setChargeStarted(time);setCharging(true)},[]);
 const endCharge=useCallback(()=>{const began=chargeRef.current,g=liveGame.current;if(began===null||!g)return;chargeRef.current=null;setCharging(false);const pos=((localNow()+clock.current-began)%1400)/1400,quality=clamp(1-Math.abs(pos-.5)*2,0,1);tone("pitch");void current.current.run({op:"pitch",code:g.code,previousPitch:g.pitchCount,type:current.current.pitchType,aim:{...aim.current},quality}).catch(()=>{})},[]);
 useEffect(()=>{if(!tabActive){chargeRef.current=null;setCharging(false);void audio.current?.suspend();return}const timer=setInterval(()=>setNow(localNow()+clock.current),40);return()=>clearInterval(timer)},[tabActive]);
 useEffect(()=>{const code=new URLSearchParams(location.search).get("match");if(!code){setRestoring(false);return}const gen=generation.current;let active=true;void request(undefined,code).then(v=>{if(active)apply(v,gen)}).catch(error=>{if(active){setError(error instanceof Error?error.message:"대결을 복구하지 못했습니다.");history.replaceState(null,"",location.pathname)}}).finally(()=>{if(active)setRestoring(false)});return()=>{active=false}},[apply]);
 useEffect(()=>{if(!tabActive||!game||game.done)return;const gen=generation.current;let alive=true,polling=false;const poll=async()=>{if(polling)return;polling=true;try{const v=await request(undefined,game.code);if(alive&&gen===generation.current){apply(v,gen);setConnected(true)}}catch{if(alive)setConnected(false)}finally{polling=false}};void poll();const timer=setInterval(poll,game.waiting?1200:240);return()=>{alive=false;clearInterval(timer)}},[tabActive,game?.code,game?.done,game?.waiting,apply]);
 useEffect(()=>{if(!tabActive||!game||game.done||game.waiting||game.mode!=="ai"||game.role!=="batter"||game.pitch&&!game.pitch.resolved)return;const g=game,gen=generation.current;const delay=g.pitch?Math.max(0,Math.max(g.pitch.releaseAt+g.pitch.flightMs,g.pitch.reaction?.at??0)+2100-(localNow()+clock.current)):450;const timer=setTimeout(()=>{if(gen===generation.current&&!lock.current)void askPitch()},delay);return()=>clearTimeout(timer)},[tabActive,game?.code,game?.pitchCount,game?.history.length,game?.waiting,game?.done]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{const el=e.target as HTMLElement;if(["INPUT","SELECT","TEXTAREA"].includes(el.tagName)||dialog.current?.open)return;if(!liveGame.current)return;if(e.code==="Space"){e.preventDefault();if(e.repeat)return;if(current.current.side==="batter")swing();else beginCharge()}const delta=.12;if(e.code.startsWith("Arrow")){e.preventDefault();aim.current={x:clamp(aim.current.x+(e.code==="ArrowRight"?delta:e.code==="ArrowLeft"?-delta:0)*(current.current.side==="pitcher"?-1:1),-2,2),y:clamp(aim.current.y+(e.code==="ArrowUp"?delta:e.code==="ArrowDown"?-delta:0),-2,2)}}};const up=(e:KeyboardEvent)=>{if(e.code==="Space"&&chargeRef.current!==null){e.preventDefault();endCharge()}};const blur=()=>{if(chargeRef.current!==null){chargeRef.current=null;setCharging(false)}};window.addEventListener("keydown",down);window.addEventListener("keyup",up);window.addEventListener("blur",blur);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up);window.removeEventListener("blur",blur)}},[swing,beginCharge,endCharge]);
 const toolsState=useRef({game,batter,pitcher,side,mode,pace,start});toolsState.current={game,batter,pitcher,side,mode,pace,start};
 useEffect(()=>{type MC={registerTool:(a:unknown,b:{signal:AbortSignal})=>void|Promise<void>};const mc=(document as Document&{modelContext?:MC}).modelContext;if(!mc)return;const c=new AbortController();for(const tool of [{name:"read_action_baseball",description:"타자/투수 시점, 선수, 투구와 볼카운트, 결과를 조회합니다.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("빈 객체를 입력해 주세요.");const s=toolsState.current;return {side:s.side,batter:s.batter,pitcher:s.pitcher,mode:s.mode,pace:s.pace,game:s.game}}},{name:"start_action_baseball",description:"화면에서 선택한 선수와 시점으로 직접 조작하는 새 야구 대결을 시작합니다.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length||toolsState.current.game)throw new Error("경기 설정 화면에서만 시작할 수 있습니다.");const v=await toolsState.current.start();if(!v)throw new Error("대결을 시작할 수 없습니다.");return {started:true,code:v.code}}}]){try{void Promise.resolve(mc.registerTool(tool,{signal:c.signal})).catch(()=>{})}catch{}}return()=>c.abort()},[]);
 async function copy(){try{await navigator.clipboard.writeText(game?.code??"");setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setError("화면의 코드를 선택해 복사해 주세요.")}}
 async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await stage.current?.requestFullscreen()}catch{setError("이 브라우저에서는 전체화면을 사용할 수 없습니다.")}}
 let status=!game?"선수를 고르고 그라운드로 들어오세요":waiting?"상대 입장 대기":done?"경기 종료":active&&!active.resolved?now<active.releaseAt?"투수가 와인드업합니다":"공을 끝까지 보세요":side==="pitcher"?"코스를 조준하고 눌렀다 놓으세요":"다음 투구 준비 중";
 return <main className="action-app"><header className="game-header"><div className="brand"><strong>DIAMOND</strong><span>KBO SABERMETRICS</span></div><div className="header-tools"><span className="data-label">{selectedSeason?selectedSeason+" 시즌 기록":game?"이전 대결 기록":"DB 선수 기록"}</span><button title={sound?"소리 끄기":"소리 켜기"} aria-label={sound?"소리 끄기":"소리 켜기"} onClick={()=>setSound(!sound)}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><button onClick={()=>dialog.current?.showModal()}><CircleHelp size={18}/><span>조작 안내</span></button></div></header>
 <div className="action-content"><div className="view-heading"><div><h1>야구 대결</h1><p className="view-description">기록으로 만난 선수들, 이제 그라운드에서 직접 상대하세요.</p></div><div className="view-switch"><button disabled={!!game} aria-pressed={side==="batter"} className={side==="batter"?"selected":""} onClick={()=>{setSide("batter");aim.current={x:0,y:0}}}><Crosshair size={16}/>타자 시점</button><button disabled={!!game} aria-pressed={side==="pitcher"} className={side==="pitcher"?"selected":""} onClick={()=>{setSide("pitcher");aim.current={x:0,y:0}}}><Target size={16}/>투수 시점</button></div></div>
 {error&&<div className="error-banner" role="alert"><span>{error}</span><button aria-label="알림 닫기" onClick={()=>setError("")}><X size={16}/></button></div>}
 <div className="game-layout"><div className="field-column"><section ref={stage} className={"play-stage "+side} aria-label={side==="batter"?"타자 시점 야구장":"투수 시점 야구장"}><div className="field-world" style={{backgroundImage:"url(/diamond/"+(side==="batter"?"batting":"pitching")+"-stadium.png)"}}>
 {tabActive&&b&&p&&<ActionScene view={game} side={side} aim={aim} clock={clock} swingTime={swingTime} localSwing={localSwing} charging={charging} chargeStarted={chargeStarted} onSwing={swing} onContact={contactSound} onChargeStart={beginCharge} onChargeEnd={endCharge} onReady={setReady3d} batterId={batter} pitcherId={pitcher}/>}</div>
 <div className="field-vignette"/><div className="score-hud"><div className="inning-label"><span>{mode==="pvp"?"PvP":"VS AI"}</span><strong>{game?Math.min(game.round+1,6):1}<small> / 6 타석</small></strong></div><div className="count-hud"><div><b>B</b>{[0,1,2].map(i=><i key={i} className={(game?.balls??0)>i?"ball-on":""}/>)}</div><div><b>S</b>{[0,1].map(i=><i key={i} className={(game?.strikes??0)>i?"strike-on":""}/>)}</div></div><div className="runs-hud"><span>득점</span><strong>{game?.score??0}<small> / 4</small></strong></div></div>
 <div className="field-top-right"><span className={"live-status "+(!connected?"offline":"")}><i/>{!connected?"재연결 중":game?waiting?"WAITING":"LIVE":"BATTING PRACTICE"}</span><button aria-label="전체화면 전환" onClick={fullscreen}><Maximize2 size={17}/></button></div>
 {!game&&(restoring||rosterLoading||!b||!p)&&<div className="stage-notice roster-stage"><h2>{restoring?"대결을 복구하고 있습니다":rosterLoading?"DB 선수 기록을 불러오고 있습니다":"선수 기록을 선택해 주세요"}</h2><p>{!rosterLoading&&!restoring?(rosterError?"선수 목록을 다시 불러온 뒤 시작할 수 있습니다.":"시즌·팀·선수 조건을 확인해 주세요."):"잠시만 기다려 주세요."}</p></div>}
 {ready3d===false&&b&&p&&<div className="stage-notice"><h2>3D 화면을 열 수 없습니다</h2><p>브라우저의 하드웨어 가속을 켜고 다시 접속해 주세요.</p></div>}
 {!game&&ready3d&&b&&p&&!restoring&&<div className="entry-hint"><span>{side==="batter"?"BATTER'S BOX":"ON THE MOUND"}</span><h2>{side==="batter"?"공을 보고, 직접 스윙하세요.":"한 구로 승부하세요."}</h2><p>{side==="batter"?"마우스로 조준 · 클릭 또는 SPACE로 스윙":"마우스로 코스 조준 · SPACE를 누른 뒤 초록 구간에 놓기"}</p></div>}
 {waiting&&<div className="stage-notice"><Users size={27}/><h2>친구가 입장하면 시작합니다.</h2><button className="invite-code" onClick={copy}>{game?.code} <Copy size={18}/></button><p>{copied?"코드를 복사했습니다":"친구에게 같은 게임 주소와 코드를 보내세요."}</p></div>}
 {done&&<div className="stage-notice end-match"><Trophy size={34}/><span>FINAL RESULT</span><h2>{game?.winner===side?"YOU WIN":"YOU LOSE"}</h2><p>6타석 · {game?.score}점 · {game?.winner==="batter"?"타자":"투수"} 승리</p><button className="primary-button" onClick={reset}>다시 그라운드로 <ArrowRight size={16}/></button></div>}
 {last&&!done&&now>=(last.contact?.at??last.bodyHit?.at??last.swingAt??last.at)&&now-last.at<1900&&<div className={"hit-result "+last.kind} key={last.id} aria-live="polite"><strong>{last.label}</strong><span>{last.contact?"타구 속도 "+Math.round(last.exitSpeed)+" km/h · "+(last.trajectory==="ground"?"땅볼":last.trajectory==="foul"?"파울 타구":"비거리 "+last.distance+" m"):last.outcome==="HBP"?"사구 출루 · +1점":last.timing!==null?(Math.abs(last.timing)<35?"타이밍 좋음":last.timing<0?"스윙이 빨랐어요":"스윙이 늦었어요"):""}</span></div>}
 {active&&now>=active.releaseAt&&<div className="pitch-hud"><strong>{active.velocity.toFixed(1)}</strong><span>km/h</span><small>{PITCH_NAMES[active.type]}</small></div>}
 {charging&&<div className="field-release"><span>RELEASE</span><div className="meter-track"><i className="sweet-spot"/><b style={{left:progress*100+"%"}}/></div><small>초록 구간에 놓으세요</small></div>}
 <div className="field-bottom"><div className="player-tag"><span>{side==="batter"?"PITCHER":"BATTER"}</span><strong>{side==="batter"?p?.name??"투수 선택":b?.name??"타자 선택"}</strong><small>{teamName((side==="batter"?p?.team:b?.team)??"",roster?.teams)}{b&&p?" · "+(side==="batter"?pitcherHandLabel(pitcher):batterHandLabel(batter,pitcher)):""}</small></div><div className="field-status">{status}</div><div className="pace-badge">{PACE_SETTINGS[pace].badge}</div></div>
 {game&&!waiting&&!done&&<div className="touch-actions">{side==="batter"?<button className="swing-touch" disabled={!canSwing} onPointerDown={e=>{e.preventDefault();e.stopPropagation();swing()}}>SWING</button>:<button className={"throw-touch "+(charging?"held":"")} disabled={!canPitch&&!charging} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);beginCharge()}} onPointerUp={endCharge} onPointerCancel={()=>{chargeRef.current=null;setCharging(false)}}>누르고<br/>놓기</button>}</div>}
 </section>
 <div className="control-deck"><div className="control-label"><MousePointer2 size={18}/><div><strong>{side==="batter"?"조준하고, 공이 도착할 때 스윙":"코스를 정하고, 정확한 릴리스"}</strong><span>{side==="batter"?"마우스 / 방향키로 조준 · 클릭 / SPACE로 스윙":"마우스 / 방향키로 조준 · SPACE 누르기 → 초록 구간에 놓기"}</span></div></div>{side==="pitcher"&&game&&!done?<div className="release-meter"><div className="meter-track"><i className="sweet-spot"/><b style={{left:progress*100+"%"}}/></div><span>{charging?"초록 구간에 놓으세요":"누른 상태로 힘을 모으세요"}</span></div>:<div className="keyboard-hint"><kbd>SPACE</kbd><span>{side==="batter"?"SWING":"RELEASE"}</span></div>}</div>
 <div className="last-pitch"><span>LAST PITCH</span>{last?<><b>{last.label}</b><span>타이밍 <strong>{last.timing===null?"—":(last.timing>0?"+":"")+last.timing+" ms"}</strong></span><span>조준 <strong>{last.aimError===null?"—":Math.round(clamp(1-last.aimError/1.2,0,1)*100)+"%"}</strong></span>{last.trajectory==="ground"?<span>타구 <strong>땅볼 · 낮게 굴러감</strong></span>:<span>비거리 <strong>{last.distance||"—"}{last.distance?" m":""}</strong></span>}</>:<p>첫 투구를 기다리고 있습니다.</p>}</div>
 </div>
 <aside className="game-sidebar"><div className="sidebar-title"><h2>{game?"대결 정보":"경기 설정"}</h2>{game&&<button className="text-button" disabled={busy} onClick={reset}><RotateCcw size={13}/>새 대결</button>}</div>
 {!game&&<div className="mode-picker"><button className={mode==="ai"?"selected":""} onClick={()=>setMode("ai")}><Zap size={15}/>AI 대결</button><button className={mode==="pvp"?"selected":""} onClick={()=>setMode("pvp")}><Users size={15}/>친구 대결</button></div>}
 {!game&&<div className="roster-controls"><label htmlFor="season-select">시즌</label><select id="season-select" value={selectedSeason??""} disabled={busy||restoring} onChange={e=>{setSeasonRequest(e.target.value?Number(e.target.value):null);setBatterSearch("");setPitcherSearch("")}}><option value="">최신 시즌</option>{(roster?.seasons??(seasonRequest?[seasonRequest]:[])).map(year=><option key={year} value={year}>{year}</option>)}</select></div>}
 {!game&&<div className={"roster-status "+(rosterError?"failed":"")} role="status">{rosterLoading?"선수 기록을 불러오는 중…":rosterError?<><span>{rosterError}</span><button onClick={()=>setRosterRetry(value=>value+1)}>다시 불러오기</button></>:roster?<><span>{roster.season} 정규시즌 · {roster.asOf} 기준</span><small>타자 {roster.batters.length}명 · 투수 {roster.pitchers.length}명</small>{(!roster.batters.length||!roster.pitchers.length)&&<p>이 시즌에는 대결에 필요한 선수 기록이 없습니다.</p>}</>:null}</div>}
 {game&&<p className="match-roster-note">{game.roster?game.roster.season+" 정규시즌 · "+game.roster.asOf+" 기록 고정":"이전 대결의 선수 기록으로 진행합니다."}</p>}
 {!game&&<button className="primary-button enter-button" disabled={busy||!ready3d||!b||!p||!roster||rosterLoading||restoring} onClick={start}>{busy?<Loader2 className="spin" size={17}/>:<ArrowRight size={17}/>} {mode==="pvp"?"대결방 만들기":side==="batter"?"타석에 들어서기":"마운드에 오르기"}</button>}
 <div className={"roster-card "+(side==="batter"?"my-player":"")}><div className="roster-label"><span>BATTER</span>{side==="batter"&&<b>YOU</b>}</div>
 {!game&&<div className="player-filters"><select aria-label="타자 팀" value={batterTeam} disabled={!roster} onChange={e=>setBatterTeam(e.target.value)}><option value="">모든 팀</option>{roster?.teams.map(team=><option key={team.code} value={team.code}>{team.name}</option>)}</select><input type="search" aria-label="타자 이름 검색" placeholder="타자 이름 검색" value={batterSearch} disabled={!roster} onChange={e=>setBatterSearch(e.target.value)}/></div>}
 <label htmlFor="batter-select">{b?.name??"타자 선택"}<span>{b?teamName(b.team,roster?.teams):""}</span></label>{b&&<div className="handedness-badge">{batterHandLabel(batter,pitcher)}</div>}
 {!game&&<select id="batter-select" aria-label="출전 타자" value={filteredBatters.some(x=>x.id===batter)?batter:""} disabled={!roster||!filteredBatters.length} onChange={e=>setBatter(e.target.value)}>{!filteredBatters.length&&<option value="">{rosterLoading?"불러오는 중":"검색 결과 없음"}</option>}{filteredBatters.map(x=><option key={x.id} value={x.id}>{playerOptionLabel(x,roster?.batters??[],roster?.teams)}</option>)}</select>}
 {b&&<><div className="mini-stats"><div><span>AVG</span><b>{numberLabel(b.AVG,3).replace(/^0/,"")}</b></div><div><span>HR</span><b>{b.HR}</b></div><div><span>OPS</span><b>{numberLabel(b.OPS,3)}</b></div></div><div className="rating-line"><span>컨택</span><i><b style={{width:(ratings?.contact??0)+"%"}}/></i><strong>{ratings?.contact??"—"}</strong></div><div className="rating-line"><span>파워</span><i><b style={{width:(ratings?.power??0)+"%"}}/></i><strong>{ratings?.power??"—"}</strong></div>{batterSource?.sampleNote&&<p className="player-sample-note">{batterSource.sampleNote}</p>}</>}
 </div>
 <div className={"roster-card pitcher-card "+(side==="pitcher"?"my-player":"")}><div className="roster-label"><span>PITCHER</span>{side==="pitcher"&&<b>YOU</b>}</div>
 {!game&&<div className="player-filters"><select aria-label="투수 팀" value={pitcherTeam} disabled={!roster} onChange={e=>setPitcherTeam(e.target.value)}><option value="">모든 팀</option>{roster?.teams.map(team=><option key={team.code} value={team.code}>{team.name}</option>)}</select><input type="search" aria-label="투수 이름 검색" placeholder="투수 이름 검색" value={pitcherSearch} disabled={!roster} onChange={e=>setPitcherSearch(e.target.value)}/></div>}
 <label htmlFor="pitcher-select">{p?.name??"투수 선택"}<span>{p?teamName(p.team,roster?.teams):""}</span></label>{p&&<div className="handedness-badge pitching">{pitcherHandLabel(pitcher)}</div>}
 {!game&&<select id="pitcher-select" aria-label="출전 투수" value={filteredPitchers.some(x=>x.id===pitcher)?pitcher:""} disabled={!roster||!filteredPitchers.length} onChange={e=>setPitcher(e.target.value)}>{!filteredPitchers.length&&<option value="">{rosterLoading?"불러오는 중":"검색 결과 없음"}</option>}{filteredPitchers.map(x=><option key={x.id} value={x.id}>{playerOptionLabel(x,roster?.pitchers??[],roster?.teams)}</option>)}</select>}
 {p&&<><div className="mini-stats"><div><span>ERA</span><b>{numberLabel(p.ERA,2)}</b></div><div><span>SO</span><b>{p.SO}</b></div><div><span>WHIP</span><b>{numberLabel(p.WHIP,2)}</b></div></div><div className="rating-line"><span>제구</span><i><b style={{width:(ratings?.control??0)+"%"}}/></i><strong>{ratings?.control??"—"}</strong></div>{pitcherSource?.sampleNote&&<p className="player-sample-note">{pitcherSource.sampleNote}</p>}{pitcherSource?.arsenalSource==="default"&&<p className="player-sample-note">수집된 구속 자료가 없어 게임 기본 구종·구속을 사용합니다.</p>}</>}
 </div>
 {side==="pitcher"?<div className="pitch-selection"><h3>구종 선택 <span>{pitcherSource?.arsenalSource==="default"?"게임 기본 구속":"수집된 평균 구속"}</span></h3><div>{pitches.map(x=><button key={x.type} className={pitchType===x.type?"selected":""} disabled={!!game&&!canPitch&&!charging} onClick={()=>setPitchType(x.type)}><span>{PITCH_NAMES[x.type]}</span><b>{x.velocity.toFixed(1)}<small> km/h</small></b></button>)}</div></div>:<div className="arsenal-preview"><span>상대 주무기</span>{pitches.slice(0,3).map(x=><div key={x.type}><span>{PITCH_NAMES[x.type]}</span><b>{x.velocity.toFixed(1)} <small>km/h</small></b><em>{x.usage.toFixed(0)}%</em></div>)}</div>}
 {!game?<><label className="speed-choice">게임 속도<select value={pace} onChange={e=>setPace(e.target.value as Pace)}>{(Object.keys(PACE_SETTINGS) as Pace[]).map(key=><option key={key} value={key}>{PACE_SETTINGS[key].label}</option>)}</select></label>{mode==="pvp"&&<form className="join-form" onSubmit={e=>{e.preventDefault();void join()}}><input aria-label="대결 코드" value={room} maxLength={8} placeholder="친구의 8자리 코드" onChange={e=>setRoom(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,""))}/><button disabled={busy||restoring||room.length!==8}>참가</button></form>}</>:<div className="in-game-help">{side==="batter"?<><Crosshair size={20}/><p>스트라이크 존의 공에 조준점을 맞추고, 공이 눈앞에 도착할 때 스윙하세요. 볼은 참을 수 있습니다.</p></>:<><Target size={20}/><p>구종과 코스를 고른 다음, 누르고 있던 키나 버튼을 초록 구간에 놓으세요.</p></>}{mode==="pvp"&&<button className="text-button" onClick={copy}>{copied?"코드 복사 완료":game.code}<Copy size={13}/></button>}{mode==="ai"&&side==="batter"&&canPitch&&error&&<button className="primary-button" onClick={askPitch}>다음 투구</button>}</div>}
 </aside></div>
 <footer><span>6타석 · 4점이면 타자 승리 · 단타/볼넷/사구 1점, 장타 2~4점</span><button className="text-button" onClick={()=>dialog.current?.showModal()}>기록과 게임 능력치 <ArrowUpRight size={13}/></button></footer></div>
 <dialog ref={dialog} className="guide"><div className="guide-head"><span>HOW TO PLAY</span><button aria-label="안내 닫기" onClick={()=>dialog.current?.close()}><X size={22}/></button></div><h2>보이는 공을, 직접 상대하세요.</h2><h3>타자 시점</h3><p>마우스를 움직이거나 화면을 드래그해 조준합니다. 클릭하거나 SPACE를 누르면 배트가 약 0.1초 뒤 조준점을 통과합니다. 공이 홈플레이트에 도착할 때 배트가 만나도록 스윙하세요. 모바일은 조준 후 SWING 버튼을 누릅니다. 방향키로도 조준할 수 있습니다.</p><p>공이 지나간 자리에 청록색 점이 남고, 다음 공이 출발할 때 지워집니다. 몸에 맞은 위치는 주황색으로 표시됩니다.</p><p>조준점의 거리와 스윙 시각이 접촉 여부를 결정합니다. 공 아래쪽을 맞히면 발사각이 높아지고, 타이밍이 빠르거나 느리면 타구 방향이 달라집니다. 보기 좋은 타이밍과 정확한 조준일수록 강한 타구가 나옵니다.</p><h3>투수 시점</h3><p>구종을 선택하고 스트라이크 존에 코스를 조준하세요. SPACE 또는 마우스를 누르고 있다가 릴리스 게이지의 초록 구간에서 놓습니다. 모바일은 화면을 드래그해 조준한 뒤 ‘누르고 놓기’ 버튼을 사용하세요. 정확하게 놓을수록 원하는 코스로 던집니다.</p><h3>승부 규칙</h3><p>3스트라이크는 삼진, 4볼은 볼넷입니다. 2스트라이크 뒤 파울은 삼진이 되지 않습니다. 스윙하지 않은 타자의 몸에 존 밖 공이 맞으면 사구로 출루합니다. 스윙 중이거나 존을 통과한 공에 맞으면 스트라이크입니다. 총 6타석, 단타·볼넷·사구 1점, 2루타 2점, 홈런 4점이며 4점 이상이면 타자가 승리합니다. 주자 이동과 9이닝은 구현 범위에 포함하지 않은 타석 액션 경기입니다.</p><h3>실제 기록과 게임 조정</h3><p>사이트 DB에 수집된 정규시즌 기록에서 시즌과 선수를 선택합니다. 이적 선수는 시즌 전체 기록을 합산합니다. 선수 목록의 기준일까지 집계한 기록을 사용하며, 대결을 시작하면 해당 기록이 고정됩니다. 이후 DB가 갱신되어도 진행 중인 대결의 능력치는 바뀌지 않습니다. 구종별 평균 구속과 구사율, 스윙·컨택 비율은 수집된 기록을 사용합니다. 구속 자료가 없는 투수는 화면에 표시한 게임 기본 구종·구속을 사용합니다. 표본이 적은 선수는 시즌을 선택할 때 표시한 안내를 참고하세요. 컨택·파워·제구 게이지, 변화구 궤적, 제구 오차, 타이밍 허용 범위와 타구 물리는 게임용 변환값입니다. 게임 속도는 연습 약 54%, 빠르게 약 87%, 실제 구속 100% 중에서 고를 수 있습니다. 1.00배에서는 표시된 구속과 18.44m를 기준으로 감속 없이 투구 시간을 계산합니다. 예를 들어 150km/h는 약 0.44초입니다.</p><p>선수의 좌우타·투구손은 DB에 저장된 선수 정보를 사용합니다. 정보가 없으면 화면에 정보 없음을 표시하고 공용 3D 모델의 기본 방향을 사용합니다. 양타자는 우투수에게 좌타석, 좌투수에게 우타석을 사용합니다. AI 투수는 실제 구사율과 존 투구 비율을 참고하며, AI 타자는 존 안팎 스윙·컨택 비율을 참고합니다. 실제 선수 얼굴을 재현하지 않은 공용 3D 캐릭터와 가상 구장 배경을 사용합니다.</p><h3>친구와 PvP</h3><p>방장이 두 선수를 고르고 타자 또는 투수를 맡으면, 친구가 반대 시점으로 참가합니다. 같은 웹사이트에 접속해 대결 코드를 입력하세요. 서로 다른 브라우저나 기기를 사용해야 합니다. 투수의 투구를 양쪽에서 같은 시각에 재생하며, 타자의 조준과 스윙 입력을 서버가 판정합니다. 네트워크 상태에 따라 타이밍 차이가 발생할 수 있습니다. 대결은 24시간 유지됩니다.</p><a href="/#records" target="_top">기록실로 이동 <ArrowUpRight size={14}/></a></dialog>
 </main>
}
